server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data
    username: root
    password: 123
  thymeleaf:
    cache: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.gao.pojo
  ##resultType="com.gao.pojo.data
    #驼峰命名
## configuration:
##   map-underscore-to-camel-case: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml



