server:
  port: 8888


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydata?useUnicode=true&characterEncoding=utf-8&severTimezone=UTC
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

  redis:
    host: localhost
    port: 6379
    password: 123

mybatis-plus:
  type-aliases-package: com.sch.pojo
   #开启sql显示
   #configuration:
   #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   #驼峰命名
  configuration:
    map-underscore-to-camel-case: true
